
cc_test(
  name = "d2s_test",
  srcs = ["d2s_test.cc"],
  deps = [
    "//ryu",
    "//third_party/gtest",
  ],
)

cc_test(
  name = "d2s_table_test",
  srcs = ["d2s_table_test.cc"],
  deps = [
    "//ryu",
    "//third_party/gtest",
  ],
)

cc_test(
  name = "f2s_test",
  srcs = ["f2s_test.cc"],
  deps = [
    "//ryu",
    "//third_party/gtest",
  ],
)

